background {
    monitor = 
    path = ~/.config/wallpapers/burning-rose.png
    blur_passes = 0
    contrast = 0.9
    brightness = 0.8
    vibrancy = 0.2
    vibrancy_darkness = 0.0
}

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# Clock
label {
    monitor =
    text = cmd[update:1000] sh -c 'date "+%I:%M"'
    color = 0xffe0def4
    font_size = 72
    position = 18%, 16%
    halign = left
    valign = center
}

# Date
label {
    monitor = 
    text = cmd[update:1000] sh -c 'date "+%A, %B %d"'
    color = 0xffe0def4
    font_size = 19
    position = 18%, 8%
    halign = left
    valign = center
}

# TODO: Profile image

# Username
shape {
    monitor = 
    size = 320, 55
    color = 0xff6e6a86
    rounding = -1
    border_size = 0
    border_color = 0xffe0def4
    rotate = 0
    xray = false
    
    position = 16%, -0%
    halign = left
    valign = center
}

label {
    monitor = 
    text = $USER 
    color = 0xffe0def4
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    font_size = 16
    position = 22%, -0%
    halign = left
    valign = center
}

# Password field
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = 0xffe0def4
    inner_color = 0xff6e6a86
    font_color = 0xffe0def4
    fade_on_empty = false
    placeholder_text = Enter password
    hide_input = false
    position = 16%, -8%
    halign = left
    valign = center
}
